'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _12135335_1128908357138252_2140847149_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("12135335_1128908357138252_2140847149_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _12135335_1128908357138252_2140847149_n1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("12135335_1128908357138252_2140847149_n1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _12137206_Cartoon_Appliences_Recorder_Stock_Vector_radio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("12137206-Cartoon-Appliences-Recorder-Stock-Vector-radio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _568f819ba81bb7a8348b4567() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("568f819ba81bb7a8348b4567", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _568f819ba81bb7a8348b45671() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("568f819ba81bb7a8348b45671", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _6cpokoaxi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("6cpokoaxi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _8074137_vector_illustration_of_Storefront_Awning_in_red_Stock_Vector_store_shop_front() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("8074137-vector-illustration-of-Storefront-Awning-in-red-Stock-Vector-store-shop-f"& _ 
                        "ront", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ac() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ac", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arus_ac() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arus ac", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property creep() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("creep", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property db0e4b44ca9ce16f09560d5194cbea47() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("db0e4b44ca9ce16f09560d5194cbea47", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property eighth_note_stem_facing_up_hi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eighth-note-stem-facing-up-hi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property esports_dota_2_quai_rung_Ogre_Mauler_jpg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("esports_dota-2_quai-rung_Ogre-Mauler.jpg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property house_icon_md() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("house-icon-md", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property luar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("luar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property meja() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("meja", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mejaa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mejaa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property meteran() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("meteran", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property meteran_yang_bersih() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("meteran yang bersih", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property music_tone_md() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("music-tone-md", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property next_icon_2970() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("next-icon-2970", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property room_938750__340() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("room-938750__340", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property small_shops_model_vector_55694() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("small-shops-model-vector-55694", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property small_shops_model_vector_556941() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("small-shops-model-vector-556941", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property steamworkshop_webupload_previewfile_375511039_preview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("steamworkshop_webupload_previewfile_375511039_preview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property stock___dota_razor_by_mizkipz_d7w2kyy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stock___dota_razor_by_mizkipz-d7w2kyy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property suara() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("suara", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tv_meja() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tv meja", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Untitled_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Untitled-1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Untitled_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Untitled-3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property victorian_bedroom_unfurnished_by_ookamikasumi_d46qd7q() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("victorian_bedroom_unfurnished_by_ookamikasumi-d46qd7q", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property victorian_bedroom_unfurnished_by_ookamikasumi_d46qd7q1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("victorian_bedroom_unfurnished_by_ookamikasumi-d46qd7q1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property victorian_study_unfurnished_by_ookamikasumi_d46qdmw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("victorian_study_unfurnished_by_ookamikasumi-d46qdmw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property victorian_study_unfurnished_by_ookamikasumi_d46qdmw1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("victorian_study_unfurnished_by_ookamikasumi-d46qdmw1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
